# Generated by Django 3.1.2 on 2020-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices',
            new_name='choice_name',
        ),
    ]
